name: rousseau_vote
description: Rousseau Voting App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3

environment:
  sdk: ">=2.6.0-dev.8.0 <3.0.0"
  flutter:  1.20.2

dependencies:
  flutter:
    sdk: flutter

  # Core
  provider: ^4.3.1
  injectable: ^0.4.0+1
  get_it: ^4.0.2
  graphql_flutter: ^3.0.1
  uni_links: ^0.4.0
  url_launcher: ^5.5.0

  sentry: ">=3.0.0 <4.0.0"
  crypto: any

  # Firebase (notifications and analytics)
  firebase_core: ^0.4.5
  firebase_messaging: ^6.0.16
  firebase_analytics: ^5.0.16

  # UI
  pinput: ^0.2.4
  webview_flutter: ^0.3.22+1
  cached_network_image: ^2.2.0+1
  flutter_html: ^1.0.0
  flutter_typeahead: ^1.8.5
  after_layout: ^1.0.7+2
  image_picker: ^0.6.7+4
  material_design_icons_flutter: ^4.0.5345
  badges: ^1.1.1
  share: ^0.6.4+3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # Localization dependencies
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  sprintf: ^4.0.2

  # Network libraries
  dio: ^3.0.9
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1
  retrofit: ^1.3.4
  json_serializable: ^3.3.0
  uuid: ^2.2.0
  jaguar_jwt: ^2.1.6

  # Storage
  flutter_secure_storage: ^3.3.3

  # File upload
  md5_plugin: ^1.0.2

dependency_overrides:
  flutter_svg: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^1.3.7+2
  build_runner: ^1.10.0

  injectable_generator: ^0.4.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - l10n/it.json
    - assets/images/
    - assets/images/badges/
    - assets/images/placeholders/
    - assets/images/socials/
    - assets/secrets/

  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

