on:
  push:
    branches:
      - testTag
name: Release Beta on Android and iOS
jobs:
  tags:
    name: Bump version and tag commit
    outputs:
      build_number: ${{ steps.buildnumber.outputs.build_number }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}
      - name: Bump version and push tag
        id: buildname
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          RELEASE_BRANCHES: testTag
          INITIAL_VERSION: 1.1.0
          DEFAULT_BUMP: patch
  android:
    name: Android Beta Release
    needs: [tags]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: 'Get Tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
      - name: Print Tag
        run: echo $BUILD_NAME $BUILD_NUMBER
        env:
          BUILD_NAME: ${{ steps.previoustag.outputs.tag }}
          BUILD_NUMBER: ${{ needs.tags.outputs.build_number }}
  ios:
    name: IOS Beta Release
    needs: [tags]
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: 'Get Tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
      - name: Print Tag
        run: echo $BUILD_NAME $BUILD_NUMBER
        env:
          BUILD_NAME: ${{ steps.previoustag.outputs.tag }}
          BUILD_NUMBER: ${{ needs.tags.outputs.build_number }}